### ISSUE TITLE
Ship Error

### ISSUE THREAD

**Issue by XenonXI** [watchdogsrox/splite#5] opened 2021-08-05 13:34 UTC
![Screenshot_2021-08-05-21-32-22-536_com bluecord](https://user-images.githubusercontent.com/82816042/128358713-309e7c49-9d0e-45ec-8668-8abe85bafbe1.jpg)

**Comment by watchdogsrox** [comment] 2021-08-05 15:07
Was caused by using absolute paths.
Fixed in 6d3db192f61a9b5aa66f7907224ed16ece5b3613

**Closed by watchdogsrox** 2021-08-05 15:07 UTC
Labels: solved
